### ISSUE TITLE
[EPIC] Use columns library in gadgets

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#1003]
A new library to format the output data in an easier way was implemented in https://github.com/kinvolk/inspektor-gadget/pull/877. However, it's not being used in all gadgets yet. The purpose of this issue is to port all gadgets to use this library. https://github.com/kinvolk/inspektor-gadget/pull/989 implemented this for the "trace capabilities" gadget. 
 
## Heads up 

A gadget needs to use JSON for the integration tests before porting to use the columns library -> https://github.com/kinvolk/inspektor-gadget/issues/719. 

## PR tracker:
- advise: Doesn't apply
- audit:
	- [x] seccomp: https://github.com/inspektor-gadget/inspektor-gadget/pull/1133
- profile:
	- [x] block-io Outputs a graph. Doesn't apply
	- [x] cpu https://github.com/inspektor-gadget/inspektor-gadget/pull/1128
- snapshot:
	- [x] process https://github.com/inspektor-gadget/inspektor-gadget/pull/1123
	- [x] socket https://github.com/inspektor-gadget/inspektor-gadget/pull/1123
- top:
	- [ ] block-io https://github.com/inspektor-gadget/inspektor-gadget/pull/1138
	- [ ] ebpf https://github.com/inspektor-gadget/inspektor-gadget/pull/1138
	- [ ] file https://github.com/inspektor-gadget/inspektor-gadget/pull/1138
	- [ ] tcp https://github.com/inspektor-gadget/inspektor-gadget/pull/1138
- trace:
	- [x] bind (https://github.com/kinvolk/inspektor-gadget/pull/934)
	- [x] capabilities (https://github.com/kinvolk/inspektor-gadget/pull/989)
	- [x] dns (https://github.com/kinvolk/inspektor-gadget/pull/990)
	- [x] exec (https://github.com/kinvolk/inspektor-gadget/pull/934)
	- [x] Fsslower https://github.com/kinvolk/inspektor-gadget/pull/1017
	- [x] Mount https://github.com/kinvolk/inspektor-gadget/pull/1009
	- [x] oomkill (https://github.com/kinvolk/inspektor-gadget/pull/1027)
	- [x] open (https://github.com/kinvolk/inspektor-gadget/pull/1030)
	- [x] network (https://github.com/inspektor-gadget/inspektor-gadget/pull/1042)
	- [x] signal (https://github.com/kinvolk/inspektor-gadget/pull/934)
	- [x] sni (https://github.com/inspektor-gadget/inspektor-gadget/pull/1119)
	- [x] tcp (https://github.com/kinvolk/inspektor-gadget/pull/934)
	- [x] tcpconnect (https://github.com/kinvolk/inspektor-gadget/pull/1026)
