### ISSUE TITLE
[EPIC] Remove cgo requirement from tracer packages

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#1126]
As we want to enable third parties to use our gadgets directly in their own environments / tools, we should make it as easy as possible. Sometimes, a significant hurdle in building tools written in Go is the requirement of CGO - hence we should try to remove as many dependencies on that as possible. Also, switching from Go to C code at runtime always comes with increased costs in terms of CPU usage, so that is another reason to avoid mixed code.

- [x] Utils & others https://github.com/inspektor-gadget/inspektor-gadget/pull/1092
- [x] Advise https://github.com/inspektor-gadget/inspektor-gadget/pull/1177
- [x] Audit https://github.com/inspektor-gadget/inspektor-gadget/pull/1176
- [x] Profile https://github.com/inspektor-gadget/inspektor-gadget/pull/1175
- [x] Snapshot (not needed)
- [x] Top https://github.com/inspektor-gadget/inspektor-gadget/pull/1174
- [x] Trace https://github.com/inspektor-gadget/inspektor-gadget/pull/1093
- [x] Traceloop https://github.com/inspektor-gadget/inspektor-gadget/pull/1140

**Comment by flyth** [comment]
All done now! Most gadgets can now work without having CGO enabled.
