### ISSUE TITLE
[RFE] Polish traceloop

### ISSUE THREAD

**Issue by eiffel-fl** [inspektor-gadget/inspektor-gadget#1159]
## Current situation

`traceloop` was ported to CO-RE, `trace API` and `columns` package in #1023.
In this PR, some comments were left as future work.

## Impact

Addressing these comments will make `traceloop` better.

## Ideal future situation

These comments should be addressed

## Implementation options

List of comments to address:
- [x] [The kernel might reuse a mntns id, so we need to keep track if this container id was detached or not. (we don't want to detach an unrelated container)](https://github.com/inspektor-gadget/inspektor-gadget/pull/1023#discussion_r1027970137). This is sort of related to #1001.
- [x] [I think those strings ("type", "collecting", "global") should be constants in a package shared between the CLI and the gadget. It could be in a single file pkg/gadget-collection/gadgets/traceloop/config/annotations.go](https://github.com/inspektor-gadget/inspektor-gadget/pull/1023#discussion_r1021951445)
- [x] [I think we should not log an error: this can happen when the ring buffers are dumped in a middle of a syscall. This can easily happen with the accept() syscall which can take an arbitrarily long time, or just a pselect6() from a shell waiting for the next command.](https://github.com/inspektor-gadget/inspektor-gadget/pull/1023#discussion_r1021804817)
- [x] [I think we should improve local-gadget to be able to start traceloop before the container.](https://github.com/inspektor-gadget/inspektor-gadget/pull/1023#discussion_r1021930512)
- [ ] [So the gadget pod output the full error from the verifier but the error returned to the kubectl-gadget CLI remains the one line summary.](https://github.com/inspektor-gadget/inspektor-gadget/pull/1023#discussion_r1021921179). WIP in #1508.
- [x] [I think doing this copy() while it is being written can be problematic too. The initial traceloop code removes the perf ring buffer from the map. Do you do that too?](https://github.com/inspektor-gadget/inspektor-gadget/pull/1023#discussion_r1021861346): Done in #1461.
- [x] [I think showing incomplete events to the user is enough. Logs of the gadget pods are normally not visible to the user, so that's not the ideal UX.](https://github.com/inspektor-gadget/inspektor-gadget/pull/1023#discussion_r1021794295)
- [x] [Syscalls unknown to strace are printed raw, with the unknown call number printed in hexadecimal form and prefixed with   "syscall_":](https://github.com/inspektor-gadget/inspektor-gadget/pull/1023#discussion_r1021787668)
- [x] [I think we should not say "strange reason": it makes it looks like it is a bug :)](https://github.com/inspektor-gadget/inspektor-gadget/pull/1023#discussion_r1021782495)
- [x] [I see you removed the typ=SYSCALL_EVENT_TYPE_CONT, so you have to rely on the size of the 2 structs (cSyscallEvent and cSyscallContEvent) being different... I find this construct fragile: if we add or remove fields in the structs, it will suddenly break.](https://github.com/inspektor-gadget/inspektor-gadget/pull/1023#discussion_r1021766594)
- [x] [This error message is user visible, so we should make it more understandable or actionable. What about the following:](https://github.com/inspektor-gadget/inspektor-gadget/pull/1023#discussion_r1021678326)
- [x] [Since this package can be used outside of kubectl-gadget and local-gadget, the comment should also say how it can be printed using the column package:](https://github.com/inspektor-gadget/inspektor-gadget/pull/1023#discussion_r1021665307)
- [x] [I think the test on event.Syscall is done in the wrong layer. tracer.go should tell whether a return value is present or not, so SetExtractor does not have to guess based on the syscall name.](https://github.com/inspektor-gadget/inspektor-gadget/pull/1023#discussion_r1021659550)
- [x] [Retval could be a struct with:](https://github.com/inspektor-gadget/inspektor-gadget/pull/1023#discussion_r1016471691)
- [x] [If we separate the Addr (0x556ec352cf00) from Content (/lib64/libc.so.6), then we can leave the choice of presentation to the client (kubectl-gadget or local-gadget).](https://github.com/inspektor-gadget/inspektor-gadget/pull/1023#discussion_r1016448379)
