### ISSUE TITLE
[EPIC] New gadgets to inspect tcp connections

### ISSUE THREAD

**Issue by alban** [inspektor-gadget/inspektor-gadget#1199]
## Current situation

Inspektor Gadget the following gadgets to inspect tcp connections:
- trace tcp
- trace tcpconnect
- trace network
- top tcp
- advise network-policy

But there are no gadgets to look at network latency, tcp drops, tcp resets and tcp retransmissions.

## Impact

Users cannot observe problems with network latency, packet drop, tcp resets and retransmissions.

## Ideal future situation

- [x] Existing gadgets should add a timestamps to events.
- [x] https://github.com/inspektor-gadget/inspektor-gadget/issues/1422
- [x] https://github.com/inspektor-gadget/inspektor-gadget/issues/1423
- [x] https://github.com/inspektor-gadget/inspektor-gadget/issues/1424
- [x] https://github.com/inspektor-gadget/inspektor-gadget/issues/1425
- [ ] https://github.com/inspektor-gadget/inspektor-gadget/issues/1546

## Implementation options

BCC has the following tools, both in legacy Python tool and CO-RE tool:

https://github.com/iovisor/bcc/blob/master/tools/tcpdrop_example.txt 
https://github.com/iovisor/bcc/blob/master/tools/tcpretrans_example.txt 
https://github.com/iovisor/bcc/blob/master/tools/tcprtt_example.txt 
https://github.com/iovisor/bcc/blob/master/tools/tcpconnlat_example.txt 

https://github.com/iovisor/bcc/tree/master/libbpf-tools

**Comment by alban** [comment]
I had a look at bcc's tcpdrop.py: it supports 2 methods:
- kprobe on `tcp_drop`
  - Support added in bcc v0.6.0 released in 2018
  - That function no longer exists in Linux 5.17
- tracepoint `skb/kfree_skb`
  - Support added in bcc v0.25.0 released in 2022)
  - Tracepoint added in Linux 5.17

Since https://github.com/torvalds/linux/commit/c504e5c2f9648a1e5c2be01e8c3f59d394192bd3 (Linux v5.17), the tracepoint  `skb/kfree_skb` includes a `reason` field which is documented in [enum skb_drop_reason](https://github.com/torvalds/linux/blob/d2d11f342b179f1894a901f143ec7c008caba43e/include/net/dropreason.h#L76-L81) (e.g. SKB_DROP_REASON_TCP_CSUM, SKB_DROP_REASON_SOCKET_RCVBUFF etc.). The bcc tcpdrop tool does not currently display the `reason` but just the stack. For kernels that support it, it would be better to display that reason instead of showing the kernel stack. This could be added in bcc as a CORE (libbpf-tools) tool.

See also: https://github.com/iovisor/bcc/issues/3533

**Comment by siegenthalerroger** [comment]
Would it be possible to have a gadget for TCP denied connections? We'd be interested in this as a way to audit the compliance of containers with their defined network policies in a generic way. OR is this already possible?
