### ISSUE TITLE
[EPIC] Implement Bring Your Own BPF gadget

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#1406]
Implement a gadget that allows users to provide the eBPF code they want to run. 

- [x] #1603
- [ ] Add support for socket enricher
- [ ] Add support for other/all categories than `trace`
- [ ] Better (and dynamic) output formatting

**Comment by mauriciovasquezbernal** [comment]
Closing in favor of https://github.com/inspektor-gadget/inspektor-gadget/issues/1929
