### ISSUE TITLE
run: Polish implementation of support for tracer gadgets

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#1801]
Initial support for containerized gadgets was merged in https://github.com/inspektor-gadget/inspektor-gadget/pull/1743. However there are still things that need to be improved there. This issue covers them: 
- [ ] https://github.com/inspektor-gadget/inspektor-gadget/pull/1825
- [ ] Support gadgets that use the Attacher interface (dns, sni, similar)
- [ ] Support gadgets that use the socket enricher 
- [x] https://github.com/inspektor-gadget/inspektor-gadget/issues/1827
- [ ] Make definition file optional
  - ref https://github.com/inspektor-gadget/inspektor-gadget/pull/1743#discussion_r1244015102
- [ ] There are not defaults for attributes in the definition file, so all of them need to be specified. 
  - We should use the defaults in [GetDefault](https://github.com/inspektor-gadget/inspektor-gadget/blob/f0abba4ffb99a7efc15b598fb5f8344b60cca43b/pkg/columns/options.go#L28). https://github.com/go-yaml/yaml/issues/165 can help to unmarshal a YAML with default values.
- [ ] https://github.com/inspektor-gadget/inspektor-gadget/issues/1875
  - At least we need to start playing with them to understand what we're missing

**Comment by mauriciovasquezbernal** [comment]
Closing in favor of https://github.com/inspektor-gadget/inspektor-gadget/issues/1929 that has a more complete list of issues.
