### ISSUE TITLE
image-based gadgets: Implement support for toppers gadgets

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#1924]
## Issue Tracker
- [x] top blockio #2989
- [ ] top ebpf #3443

See more details on https://github.com/inspektor-gadget/inspektor-gadget/issues/1924#issuecomment-2127209677

**Comment by mauriciovasquezbernal** [comment]
Fixed by https://github.com/inspektor-gadget/inspektor-gadget/pull/2132.

**Comment by blanquicet** [comment]
Reopening as this support was removed after https://github.com/inspektor-gadget/inspektor-gadget/pull/2512.

**Comment by blanquicet** [comment]
TODOs:

- [ ] #2637: As mentioned in its description, in this PR I prepare snapshotters to easily collect the outcome of all iterators so that we can emit the whole output of a snapshotter in one single batch. Currently, we are sending one entry at a time.
- [ ] https://github.com/inspektor-gadget/inspektor-gadget/pull/2709: Support sending arrays of data in a single batch and apply it to snapshotters. 
- [ ] Create new operator that combines output from all nodes on client side.
- [ ] https://github.com/inspektor-gadget/inspektor-gadget/pull/2844: Create new operator for sorting
- [ ] Create new `cutter` operator (Or maybe inside the sorter operator) to be able to specify a fixed amount of entries per update on toppers (basically implement `--max-rows` flag on client side).
- [ ] Finally, combine everything to support running toppers using arrays and the cutter, sorter and combiner operators.

**Comment by mauriciovasquezbernal** [comment]
I don't think it was fixed by #2844, reopening.

**Comment by mauriciovasquezbernal** [comment]
I think we can close this. top_file, top_tcp and top_blockio had been converted. We'll be handling top ebpf (or related functionality) on #3759.
