### ISSUE TITLE
[EPIC] Implement Image-based Gadgets 

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#1929]
Containerized gadgets were proposed in https://github.com/inspektor-gadget/inspektor-gadget/issues/1669 and its [design document](https://github.com/inspektor-gadget/inspektor-gadget/blob/main/docs/design/002-containerized-gadgets.md) was merged in https://github.com/inspektor-gadget/inspektor-gadget/pull/1856. This issue is an umbrella tracker of all implementation issues for it:

- [X] Initial Support (https://github.com/inspektor-gadget/inspektor-gadget/pull/1743)
- [X] https://github.com/inspektor-gadget/inspektor-gadget/issues/1827
- [x] https://github.com/inspektor-gadget/inspektor-gadget/issues/1917
- [x] https://github.com/inspektor-gadget/inspektor-gadget/issues/1918
- [x] https://github.com/inspektor-gadget/inspektor-gadget/issues/1919
- [x] https://github.com/inspektor-gadget/inspektor-gadget/issues/1920
- [x] https://github.com/inspektor-gadget/inspektor-gadget/issues/1921
- [x] https://github.com/inspektor-gadget/inspektor-gadget/issues/1922
- [x] https://github.com/inspektor-gadget/inspektor-gadget/issues/1923
- [ ] https://github.com/inspektor-gadget/inspektor-gadget/issues/1924
- [x] https://github.com/inspektor-gadget/inspektor-gadget/issues/1925
- [x] https://github.com/inspektor-gadget/inspektor-gadget/issues/1926
- [x] https://github.com/inspektor-gadget/inspektor-gadget/issues/1927
- [x] https://github.com/inspektor-gadget/inspektor-gadget/issues/1928
- [x] https://github.com/inspektor-gadget/inspektor-gadget/issues/1875
- [x] https://github.com/inspektor-gadget/inspektor-gadget/issues/1932
- [x] https://github.com/inspektor-gadget/inspektor-gadget/issues/2006
- [x] https://github.com/inspektor-gadget/inspektor-gadget/issues/2021
- [x] https://github.com/inspektor-gadget/inspektor-gadget/issues/2032
- [x] https://github.com/inspektor-gadget/inspektor-gadget/issues/2045
- [x] https://github.com/inspektor-gadget/inspektor-gadget/issues/2046
- [x] https://github.com/inspektor-gadget/inspektor-gadget/issues/2096
- [x] https://github.com/inspektor-gadget/inspektor-gadget/issues/2101
- [x] https://github.com/inspektor-gadget/inspektor-gadget/issues/2109
- [x] https://github.com/inspektor-gadget/inspektor-gadget/issues/2145

The following lists issues we should also handle as part of this implementation:
- [x] https://github.com/inspektor-gadget/inspektor-gadget/issues/1993
- [x] https://github.com/inspektor-gadget/inspektor-gadget/issues/2000
- [x] https://github.com/inspektor-gadget/inspektor-gadget/issues/2005
- [x] https://github.com/inspektor-gadget/inspektor-gadget/issues/2066
- [x] https://github.com/inspektor-gadget/inspektor-gadget/issues/2115
- [x] https://github.com/inspektor-gadget/inspektor-gadget/issues/2142
- [x] https://github.com/inspektor-gadget/inspektor-gadget/issues/2167

Additional issues:
- [x] https://github.com/inspektor-gadget/inspektor-gadget/issues/2202
- [ ] https://github.com/inspektor-gadget/inspektor-gadget/issues/2549
- [x] https://github.com/inspektor-gadget/inspektor-gadget/issues/2553
- [x] https://github.com/inspektor-gadget/inspektor-gadget/issues/2316
- [x] https://github.com/inspektor-gadget/inspektor-gadget/issues/2727

**Comment by mauriciovasquezbernal** [comment]
There are still some TODOs but the base mechanism was implemented. Marking this as done!
