### ISSUE TITLE
image-based gadgets: Implement builtin gadgets as image-based ones 

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#2032]
This is an umbrella issue tracking the implementation of existing builtin gadgets as containerized gadgets.

The design document has some information about the requirements to port the different gadgets (https://github.com/inspektor-gadget/inspektor-gadget/blob/main/docs/design/002-containerized-gadgets.md#reimplementing-existing-gadgets-as-containerized-gadgets), but it's still very incomplete. 

- advise
	- [ ] network-policy
	- [ ] seccomp-profile
- audit
	- [ ] seccomp
- profile
	- [ ] block-io
	- [ ] cpu
	- [ ] tcprtt
- snapshot
	- [x] process (#1866)
	- [x] socket (#1866)
- top
	- [ ] block-io
	- [ ] ebpf
	- [x] file (#2132)
	- [ ] tcp
- trace
	- [ ] bind
	- [ ] capabilities
	- [x] dns
	- [ ] exec (initial version ported in #1743, still missing arguments handling)
	- [ ] fsslower
	- [x] mount
	- [x] oomkill
	- [X] open (done in #1743)
	- [x] signal
	- [x] sni (#2194)
	- [x] tcp (#2372)
	- [X] tcpconnect  (done in #1743)
	- [x] tcpdrop (#2432)
	- [X] tcpretrans (done in #1997)
- [ ] traceloop

**Comment by mauriciovasquezbernal** [comment]
Will be tracking it on https://github.com/inspektor-gadget/inspektor-gadget/issues/2997 with individual issues per gadget.
