### ISSUE TITLE
image-base gadgets: Implement tests for Inspektor Gadget

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#2301]
The current existing tests for built-in gadgets test (1) that the different components of Inspektor Gadget (operator, container-collection, etc) are working fine and (2) that the gadget itself does it job. Now that we're focusing in https://github.com/inspektor-gadget/inspektor-gadget/issues/1929, we should adapt the test to this scenario too.

https://github.com/inspektor-gadget/inspektor-gadget/issues/2046 covers testing gadgets, this issue is about testing Inspektor Gadget itself. To start, we should test:
- [ ] eBPF programs in the gadget are loaded and attached 
- [ ] Events summited through the tracer map are read
- [ ] Right columns are created 

and many more.

It'll probably require creating some mock gadgets for testing purposes.
