### ISSUE TITLE
[RFE] Add missing features to image based gadgets

### ISSUE THREAD

**Issue by eiffel-fl** [inspektor-gadget/inspektor-gadget#2316]
- [ ] `trace_mount`: The function call should be printed (`mount("/foo/, "/bar", ...).
- [x] `trace_signal`: Signal number should be translated to signal name (9 -> `SIGKILL`) (#2630)
- [ ] `trace_exec`: Arguments column is missing (https://github.com/inspektor-gadget/inspektor-gadget/pull/2304)
- [ ] `trace_tcpdrop`: once we support bitfield to string conversion (https://github.com/inspektor-gadget/inspektor-gadget/issues/2482), update `event->tcpflags` type (https://github.com/inspektor-gadget/inspektor-gadget/pull/2477#discussion_r1483555007)
- [ ] `trace_tcpdrop`: once we support sub-structures in `struct event`, convert fields of original `proc_ctx` to struct (https://github.com/inspektor-gadget/inspektor-gadget/pull/2477#discussion_r1484672309)
- [ ] `trace_open`: provide a human readable version of [flags](https://github.com/inspektor-gadget/inspektor-gadget/blob/5fec457b500ef91545b86f1f3a0a6038d46daf97/gadgets/trace_open/program.bpf.c#L32) once we support bitfield to string conversion 
- [x] `trace_dns`: correctly parse dns name field. (#2845)
- [ ] `trace_capabilities`: https://github.com/inspektor-gadget/inspektor-gadget/issues/2908#issue-2322586619

**Comment by blanquicet** [comment]
Also, error numbers could be translated to error name, see https://github.com/inspektor-gadget/inspektor-gadget/pull/2687#pullrequestreview-1985985700.

**Comment by mauriciovasquezbernal** [comment]
I opened different issues tracking all of this:
- https://github.com/inspektor-gadget/inspektor-gadget/issues/2995
- https://github.com/inspektor-gadget/inspektor-gadget/issues/2993
- https://github.com/inspektor-gadget/inspektor-gadget/issues/2996
- https://github.com/inspektor-gadget/inspektor-gadget/issues/2992
