### ISSUE TITLE
Open comments / change requests / discussions regarding the refactoring done in #2512

### ISSUE THREAD

**Issue by flyth** [inspektor-gadget/inspektor-gadget#2653]
This is a rough list of unaddressed / still open comments or discussions from #2512. I'm not sure if all of them are still valid, but I'll try to work my way through them 😄 

I'll add more details later on and maybe sort by priority - however, feel free to edit!

* [ ] [constants for egress/ingress](https://github.com/inspektor-gadget/inspektor-gadget/pull/2512#discussion_r1495338191)
* [ ] reevaluate yaml handling (viper)
* [ ] handle requested fields [#1](https://github.com/inspektor-gadget/inspektor-gadget/pull/2512#discussion_r1498976756), [#2](https://github.com/inspektor-gadget/inspektor-gadget/pull/2512#discussion_r1540383301)
* [ ] [rename methods by removing "OCI"](https://github.com/inspektor-gadget/inspektor-gadget/pull/2512#discussion_r1507961453)
* [ ] remove or use [EventTypeGadgetID](https://github.com/inspektor-gadget/inspektor-gadget/pull/2512#discussion_r1520743703)
* [ ] [uprobe support](https://github.com/inspektor-gadget/inspektor-gadget/commit/0c4652342fda6dcee07fb83746538781783c2bf6)
* [ ] dynamically sized events from eBPF [#1](https://github.com/inspektor-gadget/inspektor-gadget/pull/2512#discussion_r1525897363)
* [ ] [nested fields in metadata](https://github.com/inspektor-gadget/inspektor-gadget/pull/2512#discussion_r1523962099)
* [ ] unit tests, especially for DataSources [#1](https://github.com/inspektor-gadget/inspektor-gadget/pull/2512#discussion_r1529251319)
* [ ] [prevent duplicate map names](https://github.com/inspektor-gadget/inspektor-gadget/pull/2512#discussion_r1526499828)
* [ ] [return error on start/stop fail](https://github.com/inspektor-gadget/inspektor-gadget/pull/2512#discussion_r1526528464) (also check stop message)
* [ ] [truncated event handling](https://github.com/inspektor-gadget/inspektor-gadget/pull/2512#discussion_r1526581419) [#1](https://github.com/inspektor-gadget/inspektor-gadget/pull/2512#discussion_r1539338861), [#2](https://github.com/inspektor-gadget/inspektor-gadget/pull/2512#discussion_r1539342917)
* [ ] [factorizing code regarding ebpf ring/perf buffers](https://github.com/inspektor-gadget/inspektor-gadget/pull/2512#discussion_r1526582690)
* [ ] [metadata validation](https://github.com/inspektor-gadget/inspektor-gadget/pull/2512#discussion_r1526501827)
* [ ] fields added by operators: naming + casing [#1](https://github.com/inspektor-gadget/inspektor-gadget/pull/2512#issuecomment-2009867085), [#2](https://github.com/inspektor-gadget/inspektor-gadget/pull/2512#discussion_r1539684347)
* [ ] [field visibility in JSON](https://github.com/inspektor-gadget/inspektor-gadget/pull/2512#discussion_r1533250948)
* [ ] timeout parameter (!)
* [ ] [implement ReportLostData](https://github.com/inspektor-gadget/inspektor-gadget/pull/2512#discussion_r1537431945)
* [ ] hostNetwork not working
* [ ] [get namespace from deployment](https://github.com/inspektor-gadget/inspektor-gadget/pull/2512#discussion_r1537940790)
* [ ] add architecture + workflow to documentation [#1](https://github.com/inspektor-gadget/inspektor-gadget/pull/2512#pullrequestreview-1958467882)
* [ ] document param handling (both internally as well as in [metadata #1](https://github.com/inspektor-gadget/inspektor-gadget/pull/2512#discussion_r1538415656)) [#2](https://github.com/inspektor-gadget/inspektor-gadget/pull/2512#issuecomment-2019787892)
* [ ] [add netns from eBPF](https://github.com/inspektor-gadget/inspektor-gadget/pull/2512#discussion_r1538451641) or improve handling in eBPF operator
* [ ] `--output` vs `--output-mode` [#1](https://github.com/inspektor-gadget/inspektor-gadget/pull/2512#discussion_r1538555714)
* [ ] [SetHidden() vs SetHiddenRecursive()](https://github.com/inspektor-gadget/inspektor-gadget/pull/2512#discussion_r1539675271)
* [ ] [logger handling in gadget-service](https://github.com/inspektor-gadget/inspektor-gadget/pull/2512#discussion_r1540379024)
* [ ] [GadgetInfo serialization](https://github.com/inspektor-gadget/inspektor-gadget/pull/2512#discussion_r1540402378)
* [ ] [jsonpretty/yaml support](https://github.com/inspektor-gadget/inspektor-gadget/pull/2512#issuecomment-2022660963) #2652

### List of PRs

#2637
#2652

**Comment by flyth** [comment]
Addressed:
* jsonpretty/yaml support
* remove run gadget
* hostNetwork information

**Comment by blanquicet** [comment]
Adding some missing tasks:

- CLI operator should use [frontends/console](https://github.com/inspektor-gadget/inspektor-gadget/pull/2652#discussion_r1550245019)
- Make code more modular: ebpf operator should know nothing about OCI. Follow [this suggestion](https://github.com/inspektor-gadget/inspektor-gadget/pull/2512#discussion_r1517948771).
- [Avoid repeated](https://github.com/inspektor-gadget/inspektor-gadget/pull/2512#discussion_r1513795852) code in metadata (to generate/update metadata file) and ebpf operator (to run gadgets).

**Comment by blanquicet** [comment]
A leftover: https://github.com/inspektor-gadget/inspektor-gadget/pull/2708

**Comment by mauriciovasquezbernal** [comment]
@flyth what's the plan with this one. Do you think we should split it in smaller issues?

**Comment by flyth** [comment]
Good question - I think a lot is already outdated, because we found other solutions. Maybe we should open separate issues for the things that are still open and important, yes.
