### ISSUE TITLE
[EPIC] Make Network Policy Advisor more useful

### ISSUE THREAD

**Issue by margamanterola** [inspektor-gadget/inspektor-gadget#373]
The idea behind the Network Policy Advisor is very cool but the generated policies are hard to understand. Part of the problem is that the policies are very big and not very clear. There are many ways of selecting pods according to their labels and our tool doesn’t necessarily pick the groupings that make the most sense for a human. 

While it’s almost impossible to generate the same thing a human would generate, we could try to improve our groupings with the goal of putting things that are common to all or many pods together. We could also improve how we observe the traffic, group also by quantity, not just by connection. Have separate policies for big services vs a lot of small services. 

Also, we currently only capture the calls to TCP connect and accept, rather than the actual traffic (based on https://github.com/weaveworks/tcptracer-bpf/). We should capture TCP and UDP traffic. The dns gadget can be used as an example of this. 

Additionally, it would be helpful to validate a policy by surfacing traffic that has been blocked, or that would be blocked if the policy was applied. Calico already has this feature and Cilium was working on it, but it would be nice to have it independent of the CNI provider. See https://github.com/box/kube-iptables-tailer for more information. 

This epic includes:
- [x] #172 
- [ ] Group generated network policies to make understanding them easier  
- [ ] Capture all TCP and UDP traffic 
- [ ] Surface traffic that is blocked (this would be using `audit network-policy`)

[All gadget/network-policy issues](https://github.com/kinvolk/inspektor-gadget/labels/gadget%2Fnetwork-policy)

**Comment by marga-kinvolk** [comment]
To capture traffic we could use network capture, which is already independent of the kernel version so it doesn't need BTF magic.

**Comment by larssb** [comment]
Oh this would be awesome! Inspektor Gadget is such a great tool. And also, if it generated easier to understand Network Policies it would be even greater. And then further, making it surmountable to convert the generated NetworkPolicies to CiliumNetworkPolicies.

Thanks. I'll monitor this issue.

**Comment by siegenthalerroger** [comment]
I just commented on #1199 about having an alternative to the `iptables-trailer`. We've been evaluating both calico and cilium for this (though a CNI neutral option would be prefered) and haven't actually found documentation that either of them can surface blocked connections without a lot of shenanigans (calico: write LOG rules that are ordered correctly, cilium: use a well-crafted hubble flow query). Is there something we've overseen with both of those (you know, apart from an enterprise option for something that is really basic IMO)
