### ISSUE TITLE
[EPIC] Make local-gadget runnable on AKS nodes 

### ISSUE THREAD

**Issue by blanquicet** [inspektor-gadget/inspektor-gadget#643]
## Description

Currently, it is not possible to run local-gadget on AKS nodes. Notice we have the following considerations: 

- Local-gadget needs to be able to run with the configuration of AKS nodes. In particular: 
  - It uses systemd v237 which does not mount /sys/fs/bpf as bpf. 
  - It uses containerd as the container runtime. 
- We need to be able to run local-gadget when Kubernetes API Server is down using the VM underlay system (az vm run-command or kubectl az run-command). It means that [these restrictions](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/run-command#restrictions) need to be considered. The most problematic is that the interactive mode is not supported.

The final goal, it to be able to run something like this:
```bash
$ kubeclt az run-command "local-gadget trace exec --timeout 60" --id "/subscriptions/$SUBSCRIPTION/resourceGroups/$NODERESOURCEGROUP/providers/Microsoft.Compute/virtualMachineScaleSets/$VMSS/virtualmachines/$INSTANCEID"
```

This epic includes the initial tasks to provide initial support on AKS nodes based on previous considerations:  
1. Local-gadget does not work on systems where /sys/fs/bpf is not of type bpf: 
    - [x] Temporary workaround: [local-gadget: Ensure /sys/fs/bpf is of type bpf #622](https://github.com/kinvolk/inspektor-gadget/pull/622)
    - [x] A proper solution needs these two issues to be solved: 
      - [x] #620 -> @alban will work on it. 
      - [x] #619  -> @mauriciovasquezbernal is working on it. 

2. Support Containerd: 
    - [x] #606. Notice it supports only Containerd CRI and not the containers that were executed outside Kubernetes (This improvement will be managed in the future. Consider possible duplication when asking docker and containerd for containers because docker will be using containerd).

3. Run local-gadget for a specific number of seconds: 
    - [x] #583
    - [x] Add the same parameter to local-gadge. It will be done with point 4. 

4. We need to be able to run gadgets on one single call: 
    - [ ] https://github.com/kinvolk/inspektor-gadget/issues/642
    - [ ] https://github.com/kinvolk/inspektor-gadget/issues/861
 
5. Make local-gadget binary compiled from main branch downloadable: 
    - We agreed it is not worth it. We will start releasing more frequently IG so the binary with the latest feature will be always available. However, we should consider in the future building it inside a container.

**Comment by mauriciovasquezbernal** [comment]
@blanquicet what about closing this issue? I think local-gadget is now runnable on AKS nodes and also on different platforms. We're just missing https://github.com/inspektor-gadget/inspektor-gadget/issues/642 and https://github.com/inspektor-gadget/inspektor-gadget/issues/861 but those issues seem independent.
