### ISSUE TITLE
[EPIC] Improve the reliability of the CI and support new platforms

### ISSUE THREAD

**Issue by blanquicet** [inspektor-gadget/inspektor-gadget#727]
# General

This is the epic that will track the activity on the CI during the next quarter.

## Change container registry

- [x] #731 

## Fix current issues on the integration-tests

There are some known issues during the integration test. Fix them to ensure that every time the tests fail is because there is actually a problem:

- [x] https://github.com/kinvolk/inspektor-gadget/issues/724
- [x] https://github.com/kinvolk/traceloop/issues/42
- [x] https://github.com/kinvolk/inspektor-gadget/issues/726

## Support new Kubernetes distributions for the integration-tests

- [x] https://github.com/kinvolk/inspektor-gadget/issues/725
- [x] https://github.com/kinvolk/inspektor-gadget/issues/783
- [x] https://github.com/kinvolk/inspektor-gadget/issues/784

## Support other architectures 
- [x] https://github.com/kinvolk/inspektor-gadget/issues/785 

## Test different kind of gadgets
- [x] https://github.com/kinvolk/inspektor-gadget/issues/808

## Improve the output of the integration-tests to make analysis easier

We have noticed that when the integration-tests fail, sometimes we don't have enough information to understand what happened or the logs are difficult to understand. To improve this aspect, we have created a list of tasks:

- [x] https://github.com/kinvolk/inspektor-gadget/issues/567 
- [x] https://github.com/kinvolk/inspektor-gadget/issues/687 
- [x] In addition, running the integration tests with `-test.v` option to have the full logs would help. However, it would make the output difficult to read unless we use tools like this: https://github.com/kinvolk/inspektor-gadget/issues/688

## Consider using a bot for long workflow jobs

We are adding more and more tests but some of them take quite a long time so it doesn't make sense to run all of them all the time. That's why we are considering using `prow` or another bot to kick CI: 

- [x] https://github.com/kinvolk/inspektor-gadget/issues/689

**Comment by mauriciovasquezbernal** [comment]
All items on this are completed, closing it!
