### ISSUE TITLE
[EPIC] pkg/gadgets: Implement unit tests 

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#817]
We have integration tests for the different gadgets in https://github.com/kinvolk/inspektor-gadget/tree/main/integration, however we aren't unit-testing each gadget. Integration tests are great and they have allowed us to catch many problems, however they are difficult to run as they require to have Inspektor Gadget deployed in a Kuberentes cluster. Also integration tests don't cover many possible cases, hence bugs like https://github.com/kinvolk/inspektor-gadget/pull/809 are not caught.

The goal of this issue is to implement unit tests for the different gadgets. We should tests things like:
- The tracer is able to capture events 
- The provided events are complete and its information is correct (pid, uid, etc.)
- The filter by container mechanism works fine
- Gadget specific flags like [`AllFiles`](https://github.com/kinvolk/inspektor-gadget/blob/v0.7.1/pkg/gadgets/top/file/tracer/tracer.go#L42) work fine

PRs /  issues tracker:

- advise:
	- [ ] network-policy
	- [ ] seccomp-profile
- audit:
	- [ ] seccomp (https://github.com/kinvolk/inspektor-gadget/issues/847)
- profile:
	- [ ] block-io (https://github.com/kinvolk/inspektor-gadget/issues/845)
	- [ ] cpu (https://github.com/kinvolk/inspektor-gadget/issues/846)
- snapshot:
	- [x] process (https://github.com/kinvolk/inspektor-gadget/issues/843)
	- [ ] socket (https://github.com/kinvolk/inspektor-gadget/issues/844)
- top:
	- [ ] block-io (https://github.com/kinvolk/inspektor-gadget/issues/839)
	- [ ] ebpf (https://github.com/kinvolk/inspektor-gadget/issues/840)
	- [ ] file (https://github.com/kinvolk/inspektor-gadget/issues/841)
	- [ ] tcp (https://github.com/kinvolk/inspektor-gadget/issues/842)
- trace:
	- [x] bind (https://github.com/kinvolk/inspektor-gadget/issues/829)
	- [x] capabilities (https://github.com/kinvolk/inspektor-gadget/issues/830)
	- [ ] dns (https://github.com/kinvolk/inspektor-gadget/issues/831)
	- [x] exec (https://github.com/kinvolk/inspektor-gadget/pull/821)
	- [ ] fsslower (https://github.com/kinvolk/inspektor-gadget/issues/832)
	- [ ] mount (https://github.com/kinvolk/inspektor-gadget/issues/833)
	- [ ] oomkill (https://github.com/kinvolk/inspektor-gadget/issues/834)
	- [x] open (https://github.com/kinvolk/inspektor-gadget/pull/821)
	- [x] signal (https://github.com/kinvolk/inspektor-gadget/issues/835)
	- [ ] sni (https://github.com/kinvolk/inspektor-gadget/issues/836)
	- [ ] tcp (https://github.com/kinvolk/inspektor-gadget/issues/837)
	- [ ] tcpconnect (https://github.com/kinvolk/inspektor-gadget/issues/838)

**Comment by mauriciovasquezbernal** [comment]
Since this is a tracker issue for all gadgets, I'll remove myself as assignee as other folks can work on it too.

**Comment by mauriciovasquezbernal** [comment]
We're in the process of moving to image based gadgets (https://github.com/inspektor-gadget/inspektor-gadget/issues/2032) and the unit tests will have to be implemented in a different way https://github.com/inspektor-gadget/inspektor-gadget/issues/2046. I'll close this issue to avoid confusion, later on we could open new issues for implemented unit tests once we convert the gadgets to be image-based.
