### ISSUE TITLE
[RFE] local-gadget: Run gadgets using directly tracers instead of the Tracer CR

### ISSUE THREAD

**Issue by blanquicet** [inspektor-gadget/inspektor-gadget#861]
## Current situation

Currently, the `local-gadget` is running the gadgets using the framework already available for the Trace CR: [AddTracer](https://github.com/kinvolk/inspektor-gadget/blob/c14168014fe3d1daf36c5fc080377f7770e50716/cmd/local-gadget/interactive/interactive.go#L91), [Operation](https://github.com/kinvolk/inspektor-gadget/blob/c14168014fe3d1daf36c5fc080377f7770e50716/cmd/local-gadget/interactive/interactive.go#L126), [Stream](https://github.com/kinvolk/inspektor-gadget/blob/c14168014fe3d1daf36c5fc080377f7770e50716/cmd/local-gadget/interactive/interactive.go#L173), [Show](https://github.com/kinvolk/inspektor-gadget/blob/c14168014fe3d1daf36c5fc080377f7770e50716/cmd/local-gadget/interactive/interactive.go#L149) and [Delete](https://github.com/kinvolk/inspektor-gadget/blob/c14168014fe3d1daf36c5fc080377f7770e50716/cmd/local-gadget/interactive/interactive.go#L204). Also the new non-interactive mode is using it: [RunTraceAndPrintStatusOutput](https://github.com/kinvolk/inspektor-gadget/blob/c14168014fe3d1daf36c5fc080377f7770e50716/cmd/local-gadget/snapshot/process.go#L50). 

## Impact

The Tracer CR framework should be used only in a Kubernetes environment, and we should not be dealing with Kubernetes stuff in the context of `local-gadget`. 

## Ideal future situation

Instead of using the Trace CR framework ([gadget-collection packages](https://github.com/kinvolk/inspektor-gadget/tree/main/pkg/gadget-collection)), we should use the gadget tracers directly ([gadget packages](https://github.com/kinvolk/inspektor-gadget/tree/main/pkg/gadgets) introduced in https://github.com/kinvolk/inspektor-gadget/issues/723). An example of using the tracers directly is available [here](https://github.com/kinvolk/inspektor-gadget/blob/main/examples/gadgets/parser/trace/exec/exec.go).

This issue aims to track the transition. Following the status per category:
  - [x] `snapshot` category: https://github.com/kinvolk/inspektor-gadget/issues/862
  - [x] `trace` category: https://github.com/kinvolk/inspektor-gadget/issues/864
  - [x] `profile` category: https://github.com/kinvolk/inspektor-gadget/issues/865
  - [x] `advise` category: https://github.com/kinvolk/inspektor-gadget/issues/866
  - [x] `audit` category: https://github.com/kinvolk/inspektor-gadget/issues/867
  - [x] `top` category: https://github.com/kinvolk/inspektor-gadget/issues/868

Notice they must be implemented using the non-interactive approach `local-gadget trace exec` or `local-gadget audit seccomp`.

This issue replaces https://github.com/kinvolk/inspektor-gadget/issues/638 as it is more detailed and updated with the new developments.
